pipeline {
    agent any 

    stages{

        atage('Build Docker Image'){
            steps {
                script{
                    dockerapp = docker.build("pldevopscloudweek/kube-news:${env.BUILD_ID}", '-f ./src/Dockerfile ./src')
                }
            }
        }

        stage ('Push Docker Image'){
            eteps{
                script{
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhubpl' ){
                       dockerapp.push('latest')
                       dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }    
        }

        stage('Deploy Kubernetes') {
            environment {
                tag_version = "${env.BUILD_ID}"
            }
            steps{
                withKubeConfig ([credentialsId: 'kubeconfigpl']){
                    sh 'sed -i "s/{{TAG}}/$tag_version/g" ./k8s/deployment.yaml'
                    sh 'kubectl apply -f ./k8s/deployment.yaml'
                }
            }    

        }


    }

}
